server:
  port: 8888
  tomcat:
    max-http-form-post-size: 1GB

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
      driver-class-name: ${ccr.datasource.driver-class-name}
      url: jdbc:mysql://${ccr.datasource.host}:${ccr.datasource.port}/${ccr.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${ccr.datasource.username}
      password: ${ccr.datasource.password}
  data:
    redis:
      host: ${ccr.redis.host}
      port: ${ccr.redis.port}
      database: ${ccr.redis.database}
      password: ${ccr.redis.password}

  servlet:
    multipart:
      enabled: true
      max-file-size: 1GB
      max-request-size: 1GB

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ccr.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


logging:
  level:
    com:
      ccr:
        mapper: debug
        service: info
        controller: info

ccr:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: qwertyuiopasdfghjklzxcvbnm
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: Authentication

    user-secret-key: qwertyuiopasdfghjklzxcvbnm
    user-token-name: token
    user-ttl: 7200000

    teacher-secret-key: qwertyuiopasdfghjklzxcvbnm
    teacher-ttl: 7200000
    teacher-token-name: Authentications

  alioss:
    endpoint: ${ccr.alioss.endpoint}
    access-key-id: ${ccr.alioss.access-key-id}
    access-key-secret: ${ccr.alioss.access-key-secret}
    bucket-name: ${ccr.alioss.bucket-name}


