services:
  ccr-server:
    build: .
    image: ccr-server
    container_name: ccr-server
    ports:
      - "8888:8888"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/campus_clothing_recycling?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      - SPRING_REDIS_PASSWORD=123456
    volumes:
      - /etc/localtime:/etc/localtime
      - /etc/timezone/timezone:/etc/timezone
    depends_on:
      - mysql
      - redis
    networks:
      - ccr-network

  mysql:
    image: mysql:8.0
    container_name: mysql-ccr
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: campus_clothing_recycling
    volumes:
      - /root/ccr/mysql/data:/var/lib/mysql
      - /root/ccr/mysql/conf:/etc/mysql/conf.d
      - /root/ccr/mysql/init:/docker-entrypoint-initdb.d
      - /etc/localtime:/etc/localtime
      - /etc/timezone/timezone:/etc/timezone
    networks:
      - ccr-network

  redis:
    image: redis:6.2-alpine
    container_name: redis-ccr
    volumes:
      - /root/ccr/redis/data:/data
      - /root/ccr/redis/conf:/usr/local/etc/redis
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone/timezone:/etc/timezone:ro
    networks:
      - ccr-network
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

  nginx:
    image: nginx:1.20.1
    container_name: nginx-ccr
    volumes:
      - /root/ccr/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - /root/ccr/nginx/html/admin:/usr/share/nginx/html/admin
      - /root/ccr/nginx/html/user:/usr/share/nginx/html/user
      - /root/ccr/nginx/html/recycler:/usr/share/nginx/html/recycler
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone/timezone:/etc/timezone:ro
    ports:
      - "18181:18181"
      - "18182:18182"
      - "18183:18183"
    command: ["nginx", "-g", "daemon off;"]
    depends_on:
      - ccr-server
    networks:
      - ccr-network

networks:
  ccr-network:
    driver: bridge